spring:
  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 150MB

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/Dr.YumYum
    driver-class-name: org.postgresql.Driver
    username: yu-sun00
    password: dbtjsdn5876@@

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jwt:
    header: Authorization
    secret: sejongUniversityDr.YumYumProjectTeamMemberNameBrokenFinger98,sigmaith,s1lv3rrud
    token-validity-in-seconds: 86400

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 73ZNHJkwvsqhMb4Y8K97
            client-secret: SUPYp2YOSc
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver

          google:
            client-id: 900826148010-fknvnc27d2vd48umofnkunn877b4c3ej.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          kakao:
            client-id: 7023afe739f54610abc77efab93f535c
            client-secret: ZmdkgaHEussQBcbQ1fifGKBCq3A5IiFD
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    capstone: DEBUG


